// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymytximfmqcubhdvkruu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlteXR4aW1mbXFjdWJoZHZrcnV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzM0NDAsImV4cCI6MjA2NTMwOTQ0MH0.tPKhBe4bFm_OhFRELbP5aowAUDGLmhyps-J-d9TCTlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);